package util;
// Generated Sep 6, 2019 11:23:48 AM by Hibernate Tools 4.3.1



/**
 * Korisnici generated by hbm2java
 */
public class Korisnici  implements java.io.Serializable {


     private String korime;
     private long jmbg;
     private String lozinka;
     private String ime;
     private String prezime;
     private byte tip;
     private String email;
     private String zanimanje;
     private String pol;
     private String pitanje;
     private String odgovor;

    public Korisnici() {
    }

    public Korisnici(String korime, long jmbg, String lozinka, String ime, String prezime, byte tip, String email, String zanimanje, String pol, String pitanje, String odgovor) {
       this.korime = korime;
       this.jmbg = jmbg;
       this.lozinka = lozinka;
       this.ime = ime;
       this.prezime = prezime;
       this.tip = tip;
       this.email = email;
       this.zanimanje = zanimanje;
       this.pol = pol;
       this.pitanje = pitanje;
       this.odgovor = odgovor;
    }
   
    public String getKorime() {
        return this.korime;
    }
    
    public void setKorime(String korime) {
        this.korime = korime;
    }
    public long getJmbg() {
        return this.jmbg;
    }
    
    public void setJmbg(long jmbg) {
        this.jmbg = jmbg;
    }
    public String getLozinka() {
        return this.lozinka;
    }
    
    public void setLozinka(String lozinka) {
        this.lozinka = lozinka;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public byte getTip() {
        return this.tip;
    }
    
    public void setTip(byte tip) {
        this.tip = tip;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getZanimanje() {
        return this.zanimanje;
    }
    
    public void setZanimanje(String zanimanje) {
        this.zanimanje = zanimanje;
    }
    public String getPol() {
        return this.pol;
    }
    
    public void setPol(String pol) {
        this.pol = pol;
    }
    public String getPitanje() {
        return this.pitanje;
    }
    
    public void setPitanje(String pitanje) {
        this.pitanje = pitanje;
    }
    public String getOdgovor() {
        return this.odgovor;
    }
    
    public void setOdgovor(String odgovor) {
        this.odgovor = odgovor;
    }




}


